### PR TITLE
Support saving user into MongDB

### PR DESCRIPTION
**Pull request by Celthi**
@takashiro 
I added two API: GET to get user and POST to create user and save to MongoDB for this issue: https://github.com/takashiro/asmodee-werewolf-server/issues/2
If the MongoDB is not enable, change the setting in app[-dev].json to false to not use MongoDB.
If the MongoDB is start, then write the ip and host in app[-dev].json to have function to work.
The front UI is not added yet.

### CODE REVIEW

**Comment by takashiro** [comment]
I've been thinking if it is possible to implement reusable RESTful APIs for user authentication, otherwise every games must implement its own version and codes are hacked everywhere.

**Comment by Celthi** [comment]
@takashiro 
Yeah. That would be a better approach if we have multiple games on one server.
The current code could be plugged into other games by copying and pasting.
So we may need to implement a node module to handle user authentication and user data store.

**Comment by Celthi** [comment]
@takashiro 
Do you mean a standard alone server that provide RESTFul API for user authentication?

**Comment by Celthi** [comment]
Close this immature PR.

**Pull request closed without merging**
